---

version: 3

images:
  base_image:
    name: ghcr.io/cloudera-labs/cldr-runner-aws:latest

dependencies:
  python:
    - pywinrm>=0.3.0
  galaxy:
    collections:
      - name: https://github.infra.cloudera.com/GOES/cloudera.infra
        type: git
        version: main
      - name: https://github.infra.cloudera.com/GOES/cloudera.runtime
        type: git
        version: devel
      - name: community.windows
        version: 2.0.0